
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - '3002:3002' 
    volumes:
      - ./src:/usr/src # Синхронизация папки src
      - ./package.json:/usr/package.json # Пересоздание контейнера при изменении package.json
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=theme_chest
    command: npm run start:dev 
    depends_on:
      - mysql
    
    


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

  mysql:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: theme_chest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d/ # добавим скрипт инициализации

volumes:
  mysql-data:
